// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.1";

// src/lib/mcp/tools/search-prestataires.ts
import { createClient } from "npm:@supabase/supabase-js@^2.99.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.1";
import { z } from "npm:zod@^3.25.76";
var PUBLIC_FIELDS = "id, slug, nom_commercial, description_courte, ville, region, prix_depart, prix_max, note_moyenne, nombre_avis, est_premium, est_verifie, photo_principale_url";
function client(ctx) {
  const token = ctx.getToken();
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: token ? { headers: { Authorization: `Bearer ${token}` } } : {},
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var search_prestataires_default = defineTool({
  name: "search_prestataires",
  title: "Rechercher des prestataires",
  description: "Recherche des prestataires mariage LesNoces actifs. Filtres optionnels : mot-cl\xE9 (nom, description), ville, r\xE9gion, cat\xE9gorie (slug).",
  inputSchema: {
    query: z.string().optional().describe("Mot-cl\xE9 libre (nom commercial, description)"),
    ville: z.string().optional().describe("Ville (match exact insensible \xE0 la casse)"),
    region: z.string().optional().describe("R\xE9gion (match exact insensible \xE0 la casse)"),
    categorie_slug: z.string().optional().describe("Slug d'une cat\xE9gorie (m\xE8re ou fille)"),
    limit: z.number().int().min(1).max(50).default(10)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, ville, region, categorie_slug, limit }, ctx) => {
    const supabase = client(ctx);
    let categorieIds = null;
    if (categorie_slug) {
      const { data: cats } = await supabase.from("categories").select("id").eq("slug", categorie_slug);
      categorieIds = (cats ?? []).map((c) => c.id);
      if (categorieIds.length === 0) {
        return { content: [{ type: "text", text: "Aucun r\xE9sultat (cat\xE9gorie inconnue)." }], structuredContent: { items: [] } };
      }
    }
    let q = supabase.from("prestataires").select(PUBLIC_FIELDS).eq("statut", "actif").limit(limit);
    if (query) q = q.or(`nom_commercial.ilike.%${query}%,description_courte.ilike.%${query}%,description.ilike.%${query}%`);
    if (ville) q = q.ilike("ville", ville);
    if (region) q = q.ilike("region", region);
    if (categorieIds) q = q.or(
      categorieIds.map((id) => `categorie_mere_id.eq.${id},categorie_fille_id.eq.${id}`).join(",")
    );
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: `Erreur: ${error.message}` }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { items: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-prestataire.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.99.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.1";
import { z as z2 } from "npm:zod@^3.25.76";
var PUBLIC_FIELDS2 = "id, slug, nom_commercial, description, description_courte, ville, region, code_postal, prix_depart, prix_max, note_moyenne, nombre_avis, site_web, urls_galerie, photo_principale_url, video_url, tags, champs_specifiques, est_premium, est_verifie, zones_intervention";
var get_prestataire_default = defineTool2({
  name: "get_prestataire",
  title: "Fiche prestataire",
  description: "Renvoie la fiche publique compl\xE8te d'un prestataire LesNoces par son slug.",
  inputSchema: {
    slug: z2.string().min(1).describe("Slug de la fiche (ex: studio-fleuriste-ephemere)")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ slug }, ctx) => {
    const token = ctx.getToken();
    const supabase = createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      global: token ? { headers: { Authorization: `Bearer ${token}` } } : {},
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const { data, error } = await supabase.from("prestataires").select(PUBLIC_FIELDS2).eq("slug", slug).eq("statut", "actif").maybeSingle();
    if (error) return { content: [{ type: "text", text: `Erreur: ${error.message}` }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Fiche introuvable ou non publi\xE9e." }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { prestataire: data }
    };
  }
});

// src/lib/mcp/tools/list-categories.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.99.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.1";
var list_categories_default = defineTool3({
  name: "list_categories",
  title: "Lister les cat\xE9gories",
  description: "Retourne l'ensemble des cat\xE9gories de prestataires LesNoces (m\xE8res + filles) avec leur slug.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    const token = ctx.getToken();
    const supabase = createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      global: token ? { headers: { Authorization: `Bearer ${token}` } } : {},
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const { data, error } = await supabase.from("categories").select("id, slug, nom, categorie_mere_id").order("nom");
    if (error) return { content: [{ type: "text", text: `Erreur: ${error.message}` }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { items: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-me.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.99.1";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.1";
var get_me_default = defineTool4({
  name: "get_me",
  title: "Mon profil",
  description: "Retourne le profil de l'utilisateur connect\xE9 (identit\xE9, r\xF4les LesNoces).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Non authentifi\xE9." }], isError: true };
    }
    const userId = ctx.getUserId();
    const supabase = createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const [profileRes, rolesRes] = await Promise.all([
      supabase.from("profiles").select("id, prenom, nom, email").eq("id", userId).maybeSingle(),
      supabase.from("user_roles").select("role").eq("user_id", userId)
    ]);
    const payload = {
      user_id: userId,
      email: ctx.getUserEmail(),
      profile: profileRes.data ?? null,
      roles: (rolesRes.data ?? []).map((r) => r.role)
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/list-my-demandes.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.99.1";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.22.1";
import { z as z3 } from "npm:zod@^3.25.76";
var list_my_demandes_default = defineTool5({
  name: "list_my_demandes_devis",
  title: "Mes demandes de devis",
  description: "Liste les demandes de devis de l'utilisateur connect\xE9 (c\xF4t\xE9 client : ses envois ; c\xF4t\xE9 prestataire : celles re\xE7ues). RLS appliqu\xE9e.",
  inputSchema: {
    limit: z3.number().int().min(1).max(50).default(20)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Non authentifi\xE9." }], isError: true };
    }
    const supabase = createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const { data, error } = await supabase.from("demandes_devis").select("id, prestataire_id, type_evenement, date_evenement, budget, message, statut, created_at").order("created_at", { ascending: false }).limit(limit);
    if (error) return { content: [{ type: "text", text: `Erreur: ${error.message}` }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { items: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "egbohbwiywgyyculswvf";
var mcp_default = defineMcp({
  name: "lesnoces-mcp",
  title: "LesNoces",
  version: "0.1.0",
  instructions: "Outils LesNoces : marketplace de prestataires de mariage. Utilise search_prestataires et get_prestataire pour explorer les fiches publiques (statut actif uniquement). list_categories renvoie la taxonomie. get_me et list_my_demandes_devis n\xE9cessitent une session utilisateur et respectent les politiques d'acc\xE8s (RLS) : un client voit ses demandes envoy\xE9es, un prestataire celles re\xE7ues.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [search_prestataires_default, get_prestataire_default, list_categories_default, get_me_default, list_my_demandes_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
