CREATE TABLE public.zones_reference (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  type text NOT NULL CHECK (type IN ('region','departement','dom','pays')),
  slug text NOT NULL UNIQUE,
  label text NOT NULL,
  zone_value text NOT NULL,
  parent_region_slug text,
  parent_region_label text,
  parent_region_zone_value text,
  dept_code text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_zones_reference_type ON public.zones_reference(type);
CREATE INDEX idx_zones_reference_parent ON public.zones_reference(parent_region_slug);

ALTER TABLE public.zones_reference ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public can read zones_reference"
  ON public.zones_reference FOR SELECT
  USING (true);

CREATE POLICY "Admins can manage zones_reference"
  ON public.zones_reference FOR ALL
  USING (has_role(auth.uid(), 'admin'::app_role) OR has_role(auth.uid(), 'super_admin'::app_role))
  WITH CHECK (has_role(auth.uid(), 'admin'::app_role) OR has_role(auth.uid(), 'super_admin'::app_role));

INSERT INTO public.zones_reference (type, slug, label, zone_value, parent_region_slug, parent_region_label, parent_region_zone_value, dept_code) VALUES
('region', 'ile-de-france', 'Île-de-France', 'ile_de_france', NULL, NULL, NULL, NULL),
('departement', 'paris', 'Paris', '75', 'ile-de-france', 'Île-de-France', 'ile_de_france', '75'),
('departement', 'seine-et-marne', 'Seine-et-Marne', '77', 'ile-de-france', 'Île-de-France', 'ile_de_france', '77'),
('departement', 'yvelines', 'Yvelines', '78', 'ile-de-france', 'Île-de-France', 'ile_de_france', '78'),
('departement', 'essonne', 'Essonne', '91', 'ile-de-france', 'Île-de-France', 'ile_de_france', '91'),
('departement', 'hauts-de-seine', 'Hauts-de-Seine', '92', 'ile-de-france', 'Île-de-France', 'ile_de_france', '92'),
('departement', 'seine-saint-denis', 'Seine-Saint-Denis', '93', 'ile-de-france', 'Île-de-France', 'ile_de_france', '93'),
('departement', 'val-de-marne', 'Val-de-Marne', '94', 'ile-de-france', 'Île-de-France', 'ile_de_france', '94'),
('departement', 'val-d-oise', 'Val-d''Oise', '95', 'ile-de-france', 'Île-de-France', 'ile_de_france', '95'),
('region', 'provence-alpes-cote-d-azur', 'Provence-Alpes-Côte d''Azur', 'provence_alpes_cote_azur', NULL, NULL, NULL, NULL),
('departement', 'alpes-de-haute-provence', 'Alpes-de-Haute-Provence', '04', 'provence-alpes-cote-d-azur', 'Provence-Alpes-Côte d''Azur', 'provence_alpes_cote_azur', '04'),
('departement', 'hautes-alpes', 'Hautes-Alpes', '05', 'provence-alpes-cote-d-azur', 'Provence-Alpes-Côte d''Azur', 'provence_alpes_cote_azur', '05'),
('departement', 'alpes-maritimes', 'Alpes-Maritimes', '06', 'provence-alpes-cote-d-azur', 'Provence-Alpes-Côte d''Azur', 'provence_alpes_cote_azur', '06'),
('departement', 'bouches-du-rhone', 'Bouches-du-Rhône', '13', 'provence-alpes-cote-d-azur', 'Provence-Alpes-Côte d''Azur', 'provence_alpes_cote_azur', '13'),
('departement', 'var', 'Var', '83', 'provence-alpes-cote-d-azur', 'Provence-Alpes-Côte d''Azur', 'provence_alpes_cote_azur', '83'),
('departement', 'vaucluse', 'Vaucluse', '84', 'provence-alpes-cote-d-azur', 'Provence-Alpes-Côte d''Azur', 'provence_alpes_cote_azur', '84'),
('region', 'auvergne-rhone-alpes', 'Auvergne-Rhône-Alpes', 'auvergne_rhone_alpes', NULL, NULL, NULL, NULL),
('departement', 'ain', 'Ain', '01', 'auvergne-rhone-alpes', 'Auvergne-Rhône-Alpes', 'auvergne_rhone_alpes', '01'),
('departement', 'allier', 'Allier', '03', 'auvergne-rhone-alpes', 'Auvergne-Rhône-Alpes', 'auvergne_rhone_alpes', '03'),
('departement', 'ardeche', 'Ardèche', '07', 'auvergne-rhone-alpes', 'Auvergne-Rhône-Alpes', 'auvergne_rhone_alpes', '07'),
('departement', 'cantal', 'Cantal', '15', 'auvergne-rhone-alpes', 'Auvergne-Rhône-Alpes', 'auvergne_rhone_alpes', '15'),
('departement', 'drome', 'Drôme', '26', 'auvergne-rhone-alpes', 'Auvergne-Rhône-Alpes', 'auvergne_rhone_alpes', '26'),
('departement', 'isere', 'Isère', '38', 'auvergne-rhone-alpes', 'Auvergne-Rhône-Alpes', 'auvergne_rhone_alpes', '38'),
('departement', 'loire', 'Loire', '42', 'auvergne-rhone-alpes', 'Auvergne-Rhône-Alpes', 'auvergne_rhone_alpes', '42'),
('departement', 'haute-loire', 'Haute-Loire', '43', 'auvergne-rhone-alpes', 'Auvergne-Rhône-Alpes', 'auvergne_rhone_alpes', '43'),
('departement', 'puy-de-dome', 'Puy-de-Dôme', '63', 'auvergne-rhone-alpes', 'Auvergne-Rhône-Alpes', 'auvergne_rhone_alpes', '63'),
('departement', 'rhone', 'Rhône', '69', 'auvergne-rhone-alpes', 'Auvergne-Rhône-Alpes', 'auvergne_rhone_alpes', '69'),
('departement', 'savoie', 'Savoie', '73', 'auvergne-rhone-alpes', 'Auvergne-Rhône-Alpes', 'auvergne_rhone_alpes', '73'),
('departement', 'haute-savoie', 'Haute-Savoie', '74', 'auvergne-rhone-alpes', 'Auvergne-Rhône-Alpes', 'auvergne_rhone_alpes', '74'),
('region', 'nouvelle-aquitaine', 'Nouvelle-Aquitaine', 'nouvelle_aquitaine', NULL, NULL, NULL, NULL),
('departement', 'charente', 'Charente', '16', 'nouvelle-aquitaine', 'Nouvelle-Aquitaine', 'nouvelle_aquitaine', '16'),
('departement', 'charente-maritime', 'Charente-Maritime', '17', 'nouvelle-aquitaine', 'Nouvelle-Aquitaine', 'nouvelle_aquitaine', '17'),
('departement', 'correze', 'Corrèze', '19', 'nouvelle-aquitaine', 'Nouvelle-Aquitaine', 'nouvelle_aquitaine', '19'),
('departement', 'creuse', 'Creuse', '23', 'nouvelle-aquitaine', 'Nouvelle-Aquitaine', 'nouvelle_aquitaine', '23'),
('departement', 'dordogne', 'Dordogne', '24', 'nouvelle-aquitaine', 'Nouvelle-Aquitaine', 'nouvelle_aquitaine', '24'),
('departement', 'gironde', 'Gironde', '33', 'nouvelle-aquitaine', 'Nouvelle-Aquitaine', 'nouvelle_aquitaine', '33'),
('departement', 'landes', 'Landes', '40', 'nouvelle-aquitaine', 'Nouvelle-Aquitaine', 'nouvelle_aquitaine', '40'),
('departement', 'lot-et-garonne', 'Lot-et-Garonne', '47', 'nouvelle-aquitaine', 'Nouvelle-Aquitaine', 'nouvelle_aquitaine', '47'),
('departement', 'pyrenees-atlantiques', 'Pyrénées-Atlantiques', '64', 'nouvelle-aquitaine', 'Nouvelle-Aquitaine', 'nouvelle_aquitaine', '64'),
('departement', 'deux-sevres', 'Deux-Sèvres', '79', 'nouvelle-aquitaine', 'Nouvelle-Aquitaine', 'nouvelle_aquitaine', '79'),
('departement', 'vienne', 'Vienne', '86', 'nouvelle-aquitaine', 'Nouvelle-Aquitaine', 'nouvelle_aquitaine', '86'),
('departement', 'haute-vienne', 'Haute-Vienne', '87', 'nouvelle-aquitaine', 'Nouvelle-Aquitaine', 'nouvelle_aquitaine', '87'),
('region', 'occitanie', 'Occitanie', 'occitanie', NULL, NULL, NULL, NULL),
('departement', 'ariege', 'Ariège', '09', 'occitanie', 'Occitanie', 'occitanie', '09'),
('departement', 'aude', 'Aude', '11', 'occitanie', 'Occitanie', 'occitanie', '11'),
('departement', 'aveyron', 'Aveyron', '12', 'occitanie', 'Occitanie', 'occitanie', '12'),
('departement', 'gard', 'Gard', '30', 'occitanie', 'Occitanie', 'occitanie', '30'),
('departement', 'haute-garonne', 'Haute-Garonne', '31', 'occitanie', 'Occitanie', 'occitanie', '31'),
('departement', 'gers', 'Gers', '32', 'occitanie', 'Occitanie', 'occitanie', '32'),
('departement', 'herault', 'Hérault', '34', 'occitanie', 'Occitanie', 'occitanie', '34'),
('departement', 'lot', 'Lot', '46', 'occitanie', 'Occitanie', 'occitanie', '46'),
('departement', 'lozere', 'Lozère', '48', 'occitanie', 'Occitanie', 'occitanie', '48'),
('departement', 'hautes-pyrenees', 'Hautes-Pyrénées', '65', 'occitanie', 'Occitanie', 'occitanie', '65'),
('departement', 'pyrenees-orientales', 'Pyrénées-Orientales', '66', 'occitanie', 'Occitanie', 'occitanie', '66'),
('departement', 'tarn', 'Tarn', '81', 'occitanie', 'Occitanie', 'occitanie', '81'),
('departement', 'tarn-et-garonne', 'Tarn-et-Garonne', '82', 'occitanie', 'Occitanie', 'occitanie', '82'),
('region', 'hauts-de-france', 'Hauts-de-France', 'hauts_de_france', NULL, NULL, NULL, NULL),
('departement', 'aisne', 'Aisne', '02', 'hauts-de-france', 'Hauts-de-France', 'hauts_de_france', '02'),
('departement', 'nord', 'Nord', '59', 'hauts-de-france', 'Hauts-de-France', 'hauts_de_france', '59'),
('departement', 'oise', 'Oise', '60', 'hauts-de-france', 'Hauts-de-France', 'hauts_de_france', '60'),
('departement', 'pas-de-calais', 'Pas-de-Calais', '62', 'hauts-de-france', 'Hauts-de-France', 'hauts_de_france', '62'),
('departement', 'somme', 'Somme', '80', 'hauts-de-france', 'Hauts-de-France', 'hauts_de_france', '80'),
('region', 'grand-est', 'Grand Est', 'grand_est', NULL, NULL, NULL, NULL),
('departement', 'ardennes', 'Ardennes', '08', 'grand-est', 'Grand Est', 'grand_est', '08'),
('departement', 'aube', 'Aube', '10', 'grand-est', 'Grand Est', 'grand_est', '10'),
('departement', 'marne', 'Marne', '51', 'grand-est', 'Grand Est', 'grand_est', '51'),
('departement', 'haute-marne', 'Haute-Marne', '52', 'grand-est', 'Grand Est', 'grand_est', '52'),
('departement', 'meurthe-et-moselle', 'Meurthe-et-Moselle', '54', 'grand-est', 'Grand Est', 'grand_est', '54'),
('departement', 'meuse', 'Meuse', '55', 'grand-est', 'Grand Est', 'grand_est', '55'),
('departement', 'moselle', 'Moselle', '57', 'grand-est', 'Grand Est', 'grand_est', '57'),
('departement', 'bas-rhin', 'Bas-Rhin', '67', 'grand-est', 'Grand Est', 'grand_est', '67'),
('departement', 'haut-rhin', 'Haut-Rhin', '68', 'grand-est', 'Grand Est', 'grand_est', '68'),
('departement', 'vosges', 'Vosges', '88', 'grand-est', 'Grand Est', 'grand_est', '88'),
('region', 'pays-de-la-loire', 'Pays de la Loire', 'pays_de_la_loire', NULL, NULL, NULL, NULL),
('departement', 'loire-atlantique', 'Loire-Atlantique', '44', 'pays-de-la-loire', 'Pays de la Loire', 'pays_de_la_loire', '44'),
('departement', 'maine-et-loire', 'Maine-et-Loire', '49', 'pays-de-la-loire', 'Pays de la Loire', 'pays_de_la_loire', '49'),
('departement', 'mayenne', 'Mayenne', '53', 'pays-de-la-loire', 'Pays de la Loire', 'pays_de_la_loire', '53'),
('departement', 'sarthe', 'Sarthe', '72', 'pays-de-la-loire', 'Pays de la Loire', 'pays_de_la_loire', '72'),
('departement', 'vendee', 'Vendée', '85', 'pays-de-la-loire', 'Pays de la Loire', 'pays_de_la_loire', '85'),
('region', 'normandie', 'Normandie', 'normandie', NULL, NULL, NULL, NULL),
('departement', 'calvados', 'Calvados', '14', 'normandie', 'Normandie', 'normandie', '14'),
('departement', 'eure', 'Eure', '27', 'normandie', 'Normandie', 'normandie', '27'),
('departement', 'manche', 'Manche', '50', 'normandie', 'Normandie', 'normandie', '50'),
('departement', 'orne', 'Orne', '61', 'normandie', 'Normandie', 'normandie', '61'),
('departement', 'seine-maritime', 'Seine-Maritime', '76', 'normandie', 'Normandie', 'normandie', '76'),
('region', 'bretagne', 'Bretagne', 'bretagne', NULL, NULL, NULL, NULL),
('departement', 'cotes-d-armor', 'Côtes-d''Armor', '22', 'bretagne', 'Bretagne', 'bretagne', '22'),
('departement', 'finistere', 'Finistère', '29', 'bretagne', 'Bretagne', 'bretagne', '29'),
('departement', 'ille-et-vilaine', 'Ille-et-Vilaine', '35', 'bretagne', 'Bretagne', 'bretagne', '35'),
('departement', 'morbihan', 'Morbihan', '56', 'bretagne', 'Bretagne', 'bretagne', '56'),
('region', 'bourgogne-franche-comte', 'Bourgogne-Franche-Comté', 'bourgogne_franche_comte', NULL, NULL, NULL, NULL),
('departement', 'cote-d-or', 'Côte-d''Or', '21', 'bourgogne-franche-comte', 'Bourgogne-Franche-Comté', 'bourgogne_franche_comte', '21'),
('departement', 'doubs', 'Doubs', '25', 'bourgogne-franche-comte', 'Bourgogne-Franche-Comté', 'bourgogne_franche_comte', '25'),
('departement', 'jura', 'Jura', '39', 'bourgogne-franche-comte', 'Bourgogne-Franche-Comté', 'bourgogne_franche_comte', '39'),
('departement', 'nievre', 'Nièvre', '58', 'bourgogne-franche-comte', 'Bourgogne-Franche-Comté', 'bourgogne_franche_comte', '58'),
('departement', 'haute-saone', 'Haute-Saône', '70', 'bourgogne-franche-comte', 'Bourgogne-Franche-Comté', 'bourgogne_franche_comte', '70'),
('departement', 'saone-et-loire', 'Saône-et-Loire', '71', 'bourgogne-franche-comte', 'Bourgogne-Franche-Comté', 'bourgogne_franche_comte', '71'),
('departement', 'yonne', 'Yonne', '89', 'bourgogne-franche-comte', 'Bourgogne-Franche-Comté', 'bourgogne_franche_comte', '89'),
('departement', 'territoire-de-belfort', 'Territoire de Belfort', '90', 'bourgogne-franche-comte', 'Bourgogne-Franche-Comté', 'bourgogne_franche_comte', '90'),
('region', 'centre-val-de-loire', 'Centre-Val de Loire', 'centre_val_de_loire', NULL, NULL, NULL, NULL),
('departement', 'cher', 'Cher', '18', 'centre-val-de-loire', 'Centre-Val de Loire', 'centre_val_de_loire', '18'),
('departement', 'eure-et-loir', 'Eure-et-Loir', '28', 'centre-val-de-loire', 'Centre-Val de Loire', 'centre_val_de_loire', '28'),
('departement', 'indre', 'Indre', '36', 'centre-val-de-loire', 'Centre-Val de Loire', 'centre_val_de_loire', '36'),
('departement', 'indre-et-loire', 'Indre-et-Loire', '37', 'centre-val-de-loire', 'Centre-Val de Loire', 'centre_val_de_loire', '37'),
('departement', 'loir-et-cher', 'Loir-et-Cher', '41', 'centre-val-de-loire', 'Centre-Val de Loire', 'centre_val_de_loire', '41'),
('departement', 'loiret', 'Loiret', '45', 'centre-val-de-loire', 'Centre-Val de Loire', 'centre_val_de_loire', '45'),
('region', 'corse', 'Corse', 'corse', NULL, NULL, NULL, NULL),
('departement', 'corse-du-sud', 'Corse-du-Sud', '2A', 'corse', 'Corse', 'corse', '2A'),
('departement', 'haute-corse', 'Haute-Corse', '2B', 'corse', 'Corse', 'corse', '2B'),
('dom', 'guadeloupe', 'Guadeloupe', '971', NULL, NULL, NULL, NULL),
('dom', 'martinique', 'Martinique', '972', NULL, NULL, NULL, NULL),
('dom', 'guyane', 'Guyane', '973', NULL, NULL, NULL, NULL),
('dom', 'la-reunion', 'La Réunion', '974', NULL, NULL, NULL, NULL),
('dom', 'mayotte', 'Mayotte', '976', NULL, NULL, NULL, NULL),
('pays', 'belgique', 'Belgique', 'belgique', NULL, NULL, NULL, NULL),
('pays', 'luxembourg', 'Luxembourg', 'luxembourg', NULL, NULL, NULL, NULL),
('pays', 'suisse', 'Suisse', 'suisse', NULL, NULL, NULL, NULL),
('pays', 'monaco', 'Monaco', 'monaco', NULL, NULL, NULL, NULL);